version: '2.2'
services:
  app:
    container_name: modular-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - elasticsearch
    volumes:
      - ./:/app
    working_dir: /app

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: modular
      MYSQL_USER: root
    volumes:
      - ./docker/dev/my.cnf:/etc/mysql/conf.d/my.cnf

  dbmate:
    image: amacneil/dbmate:v1.9.0
    volumes:
      - ./db:/db
    env_file:
      - .env.docker

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - 5601:5601
